# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # default realization for RequestDecoderInterface
    App\Service\RequestDecoder\RequestDecoder: ~
    App\Service\RequestDecoder\RequestDecoderInterface: '@App\Service\RequestDecoder\RequestDecoder'

    # default realization for PaymentUtilsInterface
    App\Service\PaymentUtils\PaymentUtils: ~
    App\Service\PaymentUtils\PaymentUtilsInterface: '@App\Service\PaymentUtils\PaymentUtils'
    
    # default realization for RequestDecoderInterface
    # App\Service\PaymentProcessor: ~
    # App\Service\PaymentProcessorInterface: '@App\Service\RequestDecoder\RequestDecoder'

    # default realization for SerializerInterface
    app.serializer:
      class: App\Service\Serializer\Serializer
      arguments:
        $normalizers:
          - '@serializer.normalizer.constraint_violation_list'
          - '@serializer.normalizer.datetimezone'
          - '@serializer.normalizer.datetime'
          - '@serializer.normalizer.dateinterval'
          - '@serializer.normalizer.data_uri'
          - '@serializer.normalizer.json_serializable'
          - '@serializer.normalizer.problem'
          - '@serializer.normalizer.uid'
          - '@serializer.normalizer.form_error'
          - '@serializer.normalizer.backed_enum'
          - '@serializer.normalizer.object'
        $encoders: 
          - '@serializer.encoder.json'
        
    App\Service\Serializer\SerializerInterface: '@app.serializer'
  
    app.validate_dto:
      class: App\Service\Validator\AnnotationHandler\ValidateDtoHandler
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }